# Generated by Django 3.1.4 on 2021-02-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_terms_and_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAux',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user', verbose_name='user')),
                ('counter', models.IntegerField(verbose_name='counter')),
            ],
        ),
    ]
