# Generated by Django 3.1.4 on 2021-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='simple_answer',
            field=models.CharField(choices=[('-', '-'), ('si', 'Sí'), ('no', 'No')], default='-', max_length=3),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Neutro'), (1, 'Positivo'), (-1, 'Negativo')], default=0),
        ),
    ]
